___
<a href='http://www.kgptalkie.com'><img src='../kgptalkie_strips.png'/></a>
___

<center><em>Copyright by KGPTalkie</em></center>
<center><em>For free ML tutorials, visit us at <a href='http://www.kgptalkie.com'>www.kgptalkie.com</a> and <a href='http://www.youtube.com/kgptalkie'>www.youtube.com/kgptalkie</a> </em></center>

# Working with Files in Python

## String Formatter 

In [ ]:
name = 'KGP Talkie is my youtube channel name'
follower = '30k'

In [ ]:
print('name', 'follower')
print(name, follower)

In [ ]:
ds = [('python', 50), ('tensorflow', 100), ('nlp', 200)]

In [ ]:
print(ds)

In [ ]:
for info in ds:
    print(info[0], info[1])

In [ ]:
for info in ds:
    print(f'{info[0]:{20}} {info[1]}')

In [ ]:
#>, <, ^
for info in ds:
    print(f'{info[0]:{20}} {info[1]:.>{5}}')

## Working with Files 

In [ ]:
file = open('data/data.txt', 'w')

data = 'this is sentence one'
file.write(data)
file.close()

In [ ]:
len(data)

In [ ]:
file = open('data/data.txt', 'a')

data = '\t this is sentence three'
file.write(data)
file.close()

In [ ]:
file = open('data/data1.txt', 'a') # a if file is there then r+w otherwise w

data = 1
file.write(str(data))
file.close()

In [ ]:
file = open('data/data2.txt', 'w') # a if file is there then r+w otherwise w

data = [1, 'one', 'this is two', 2.3]
for d in data:
    file.write(str(d))
    file.write(',')
file.close()

In [ ]:
with open('data/data3.txt', 'w') as file:
    data = [1, 'one', 'this is two', 2.3]
    for d in data:
        file.write(str(d))
        file.write('\n')

## Working with Read mode 

In [ ]:
file = open('data/data3.txt', 'r')

In [ ]:
file.seek(0)
file.read().splitlines()

In [ ]:
file.seek(0)
file.readlines()

In [ ]:
file.seek(0)
data = file.read().splitlines()
file.close()

In [ ]:
data

In [ ]:
eval(data[-1])

In [ ]:
for index, d in enumerate(data):
    try:
        data[index] = eval(d)
    except:
        pass

In [ ]:
data

## Reading and Writing .CSV and .TSV Files with Pandas 

In [ ]:
import pandas as pd

In [ ]:
pd.read_csv('data/data3.txt', header= None)

In [ ]:
l = [(1, 'one'), (2, 'two'), (3, 'three')]
df = pd.DataFrame(l, columns=['digit', 'figure'])
df.to_csv('data/digit.csv', sep = ',', index = False)

In [ ]:
pd.read_csv('data/digit.csv')

In [ ]:
pd.read_csv('data/moviereviews.tsv', sep = '\t')

In [ ]:
df.to_csv('data/digit.tsv', sep = '\t', index = None)

# Reading and Writing .XLSX Files with Pandas

In [ ]:
df.to_excel('data/digit_sheet.xlsx', index = None, sheet_name='digit')

In [ ]:
df.to_excel('data/digit_sheet.xlsx', index = None, sheet_name='digit1')

In [ ]:
writer = pd.ExcelWriter('data/digit_sheet.xlsx', engine = 'xlsxwriter')
df.to_excel(writer, index = None, sheet_name='digit1')
df.to_excel(writer, index = None, sheet_name='digit2')
writer.save()
writer.close()

## Reading and Writing .JSON Files 

JSON (JavaScript Object Notation) is a popular data format used for representing structured data. It's common to transmit and receive data between a server and web application in JSON format.

In [ ]:
import json

In [ ]:
data_dict = {"one": "1", "two":"2"}

In [ ]:
type(data_dict)

In [ ]:
data_str = '{"one": "1", "two":"2"}'
type(data_str)

In [ ]:
#load(), loads(), dump(), dumps()

In [ ]:
json.loads(data_str)

In [ ]:
json.dumps(data_dict)

In [ ]:
file = open('data/data.json', 'w')
json.dump(data_str, file)
file.close()

In [ ]:
file = open('data/data.json', 'r')
json_data = json.load(file)
file.close

In [ ]:
json.loads(json_data)

## Reading Files from URL Links 

https://datahub.io/core/global-temp/r/monthly.json

https://raw.githubusercontent.com/laxmimerit/All-CSV-ML-Data-Files-Download/master/ecommerce.csv


In [ ]:
pd.read_csv('https://raw.githubusercontent.com/laxmimerit/All-CSV-ML-Data-Files-Download/master/ecommerce.csv')

In [ ]:
pd.read_json('https://datahub.io/core/global-temp/r/monthly.json')

## Extract Text Data From PDF 

In [ ]:
# !pip install PyPDF2

In [ ]:
import PyPDF2 as pdf

In [ ]:
file = open('data/NLP.pdf', 'rb')

In [ ]:
reader = pdf.PdfFileReader(file)

In [ ]:
reader

In [ ]:
help(reader)

In [ ]:
reader.getIsEncrypted()

In [ ]:
reader.getDocumentInfo()

In [ ]:
reader.getNumPages()

In [ ]:
page1  = reader.getPage(0).extractText()

In [ ]:
page1

In [ ]:
with open('data/pdf_text.txt', 'w') as file1:
    for i in range(reader.getNumPages()):
        page  = reader.getPage(i).extractText()
        file1.write(page)
        file1.write('\n')

## Record the Audio and Convert to Text

In [ ]:
# pip install SpeechRecognition
# conda update --force conda
# conda install pyaudio

In [1]:
import speech_recognition as sr

In [2]:
r = sr.Recognizer()

In [4]:
with sr.Microphone() as source:
    print('Say Something...')
    audio = r.listen(source, timeout = 10)
    
    try:
        text = r.recognize_google(audio)
        print('You were saying:')
        print(text)
    except:
        print('Sorry. Please try again.')

Say Something...
You were saying:
hello guys I will come to you in this video thank you so much for watching it I see you in next lesson


## Convert Audio in Text Data 

In [9]:
import speech_recognition as sr

In [17]:
import numpy as np

In [13]:
from scipy.io import wavfile

In [14]:
fs, data = wavfile.read('data/laxmikant.wav')

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: WavFileWarning: Chunk (non-data) not understood, skipping it.
  """Entry point for launching an IPython kernel.


In [15]:
fs

44100

In [16]:
data

array([[-9.1552734e-05, -9.1552734e-05],
       [-6.1035156e-05, -6.1035156e-05],
       [-6.1035156e-05, -9.1552734e-05],
       ...,
       [-1.2207031e-04, -1.8310547e-04],
       [-1.2207031e-04, -9.1552734e-05],
       [-6.1035156e-05, -9.1552734e-05]], dtype=float32)

In [20]:
y = (np.iinfo(np.int32).max * (data/np.abs(data).max())).astype(np.int32)

In [18]:
np.iinfo(np.int32).max

2147483647

In [19]:
(data/np.abs(data).max())

array([[-0.00018557, -0.00018557],
       [-0.00012372, -0.00012372],
       [-0.00012372, -0.00018557],
       ...,
       [-0.00024743, -0.00037115],
       [-0.00024743, -0.00018557],
       [-0.00012372, -0.00018557]], dtype=float32)

In [21]:
y

array([[-398518, -398518],
       [-265679, -265679],
       [-265679, -398518],
       ...,
       [-531358, -797037],
       [-531358, -398518],
       [-265679, -398518]])

In [22]:
wavfile.write('data/laxmikant_int.wav', fs, y)

In [23]:
r = sr.Recognizer()

In [25]:
with sr.AudioFile('data/laxmikant_int.wav') as source:
    audio = r.listen(source)
    
    try:
        text = r.recognize_google(audio)
        print('Working on...')
        print(text)
    except:
        print('Sorry. Try again.')

Working on...
hello everyone how are you I am sure all of you are enjoying this lesson and I would like to also request you to please leave your rating and if you have any doubts you can comment your questions in the question and answer section


##  Text to Speech Conversion

In [26]:
text = 'hello everyone how are you I am sure all of you are enjoying this lesson and I would like to also request you to please leave your rating and if you have any doubts you can comment your questions in the question and answer section'

In [27]:
!pip install gTTS

  Created wheel for gtts-token: filename=gTTS_token-1.1.3-py3-none-any.whl size=4100 sha256=04a0d4a9f35d1b143fbbdadfaa1daf6628aaeba6a526a980e80a010c26ddf32e
  Stored in directory: c:\users\kgptalkie\appdata\local\pip\cache\wheels\c1\78\25\81270af5521d88ea8db7da5d4f64872673976eb9692bcb0c13
Successfully built gtts-token


In [28]:
from gtts import gTTS as g

In [29]:
obj = g(text = text)
obj.save('data/laxmi_gtts.mp3')

In [30]:
spanish = "Hola, te doy la bienvenida en esta lección. Dale me gusta y suscríbete a este canal. Gracias"

In [31]:
obj = g(text = spanish)
obj.save('data/laxmi_gtts_spanish.mp3')

# Other Resources
|  ML Course | Description |
|:---|:---|
| [**Data Visualization in Python Masterclass™: Beginners to Pro**](https://bit.ly/udemy95off_kgptalkie) |  Learn to build Machine Learning and Deep Learning models using Python and its libraries like Scikit-Learn, Keras, and TensorFlow. |
| [**Python for Machine Learning: A Step-by-Step Guide**](https://bit.ly/ml-ds-project) | Learn to build Machine Learning and Deep Learning models using Python and its libraries like Scikit-Learn, Keras, and TensorFlow. |
| [**Python for Linear Regression in Machine Learning**](https://bit.ly/regression-python) | Learn to build Linear Regression models using Python and its libraries like Scikit-Learn. |
| [**Introduction to Spacy 3 for Natural Language Processing**](https://bit.ly/spacy-intro) | Learn to build Natural Language Processing models using Python and its libraries like Spacy. |
| [**Advanced Machine Learning and Deep Learning Projects**](https://bit.ly/kgptalkie_ml_projects) | Learn to build Advanced Machine Learning and Deep Learning models using Python and transformer models like BERT, GPT-2, and XLNet. |
| [**Natural Language Processing in Python for Beginners**](https://bit.ly/intro_nlp) | Learn to build Natural Language Processing Projects using Spacy, NLTK, and Gensim, and transformer models like BERT, GPT-2, and XLNet. |
| [**Deployment of Machine Learning Models in Production in Python**](https://bit.ly/bert_nlp) |  Learn to deploy Machine Learning and Deep Learning models using Python and its libraries like Flask, Streamlit, and NGINX. |
| [**R 4.0 Programming for Data Science - Beginners to Pro**](https://bit.ly/r4-ml) | Learn to build Machine Learning and Deep Learning models using R and its libraries like caret, tidyverse, and keras. |
